language: php
sudo: false

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "qs+10MvpYCx5fMJKv9fVpKYP3Ksq4rY3cnSeOOrGqHAKjnQ2w5KRh5ZrMTHmwxLKdoJHpwUoBGi0j4a5Q0Ln7C3Yi9xr3y9Ne7pW1i4hyq+y2D6IzGH4+XQFICw5W1UhBHPGKQr3BXJJs/ZjbyUa6qUlBbZbBuvYZ8iPS2X3b/gTHJvNRoNuQkhKZeZfQ+mmcGxKxQQd4Xlb0W/BsX0h3br/TOnR7JU9t9CiGJfSM6AIX0IIEl8s1pZhbiZFP2JpEt3U7fCBH9G56CcIRJtnN5AGTXSF0SOuYpzhxm4Fa2ylZQ+VThuQSul/PRZtZj1aaAgKgiv071Pu8hComa2XT+kjV6GiOT+Z0RfAGoaL7Areyf4U1zXr2NLZnjR4kWzXm+Eb/o/pwIuXzhsEVs3njsgcKha9spZqlZziwyqRsnfFk38Uw+DiianBK1YELSDa2QRsoV9BPlIc3Ny7kTXMJCSSk0l8nRZtNuzOaiG+ir+u3h2DY732xFmT58nPsFQ5RoWNfLX5xUhfQpBNdHvWfFt85rG6+tVp9hKlidGDa1giWvntaSdwB9IGilDuehcDiJ02P2eLAAxeNaMk34nm1Y3z+js6wqzdTLKSASfwtu1FfppKjHuBt+Iui8Y0e4Szp9w8ZafDwO+ADnNJI6NZQ5lAMNDuq5BCrFqdbuBwZwI="

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
