language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "J3lL5HUf6wlx2THFmUXDYL8s4QsJgw/P7DD1RFbVT4CkkIugGRkD+2eVM+Ss9rzpfQq0llZi2K6B8+zk4ySXEBn5/X4PLTpYda+oiNP4uKTcBNcD9n6IjeKenExI2i2LEURJ1r52YIpPoB/iSLsxJ059DFSc0RzHse7yoLI9vx/O05r4caVUsnPUsHaBY9/GDWiPe7cuLD2le8y+0gPqc0KXKxogxBGYrhXc1XdQXTg90/nbjdNf8d+acx1v7QXJrTeC/lY6T5Tskn+TAZknJKCp36DulFS6yl7NXMsz0GWj5J4PyNfTKOlosfRgzjoa2hh/99HL8IXG5uUsKYEKE37oICOgwYe27e+VsrxXTDCseSXhYUF1ngF6BWw9fM8u12SqujaV5ScA6Cu0oZzmCq4tmqM0B3iZ+sy852+q1ePzRd9os9FADLjNMYKQbJ+OCeOV+4xZcGrHdspqwJ/cXan8gtOmWXM94WkRv+4SuQ8qT9VXhv8TUfBCax7A8QQgQPx6k9Z8OhynBPa1DHLalMOS51BwzO2tnqRQoUO5pWWARHeK9V7nut7O7kTZzaSj1+gb2dFRydjencgcXfG/A5eI7Rnc6S92v7fU5o2bPyO42Ym76bx5eZb/WSCLrfVjwBqVxwIZcm1ngn/3TTdlg1cX22sdU40u37LP8XFQAeg="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
