language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "qDccXAzF8ecpqKnfKpwzP94VNuDXhRSzx1zSnVvANBCZtLtstRv0YQtNoZV8H9HoPDZ+SAVvBRetLlDPhVx+egTsnbcKIXBdAQmyMsb0GeXhvNCdLUY7zk/YpFImBCmhtvspPwFb0+/BDXjL64vyiPKDDCPXdRkH2MbYPHBd8JVuj0X/69aRnZkpVmelDbSAbmV+JMygzwdF4YRes4YkF7ZBgdKOIH8kUS1S7l+lyFZCtW7BdQQJDbSIHkpBTgG9PwWk22agFjvbx2uYwwL7dbzWYx1YB3+vyK6qPtuZO1Q6Fto+69aL7vLSzUMSg/uhkU7L7uJ23Y3nr+Q3PTHPTPPRBKseoavkR4l7udg1/4pAIa9FKssuZUtvWEfX/7b2dr5nj14QblHGvj1HvJLhwW4JOHg5C1fyHMbmpa89sh+ZiDV6WJLPxtR7ZSPsN9FpRhUb9XanfhPHBA0DOf4NKR7OWbPEUxNcKj/ecweUraBB4bucsc1GfEw58ZBbWp1Tj5dcCskdA/LzPXzvH4obgS3Db/bdVqmKWHb8szzuy7G/+E6E5ieyoWBlrQQGG1X2oyhpCtFOzBdtzHRrAJcJP53x99qXHeheDqgMZLJuWcADwkN5wdhBvyP9Vy+EBlHtNYiLX2CcudGxaSl0FO8zv/t9S4OGSsoM4E4VkGBd7+E="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - sonar-scanner
